### ISSUE TITLE
`patent-test` missing .txt files

### ISSUE THREAD

**Issue by vladtco** [AdamMeyers/The_Termolator#5]
```
The Output File is: surgery
background files processed? True
web-based filter True
max number of terms? 30000
keep terms? 5000
termolator path /opt/termolator/termolator_app
shared general filename (webscore, lemmas, etc.) False
use previous saved pickle file for terms patent.pkl
Running Step 1: finding inline terms for foreground files
Processing background files
Traceback (most recent call last):
  File "/opt/termolator/termolator_app/term_utilities.py", line 1133, in get_my_string_list
    instream = open(input_file)
FileNotFoundError: [Errno 2] No such file or directory: 'background/US20070000135A1-20070104.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/termolator/termolator_app/make_termolator_fact_txt_files.py", line 22, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/opt/termolator/termolator_app/make_termolator_fact_txt_files.py", line 20, in main
    create_termolotator_fact_txt_files(input_file,txt2_file,txt3_file,fact_file)
  File "/opt/termolator/termolator_app/termolator_fact_txt.py", line 116, in create_termolotator_fact_txt_files
    inlinelist  = get_my_string_list(input_file)
  File "/opt/termolator/termolator_app/term_utilities.py", line 1136, in get_my_string_list
    instream = open(input_file,encoding='ISO-8859-1')
FileNotFoundError: [Errno 2] No such file or directory: 'background/US20070000135A1-20070104.txt'
Calling Java Consule TJet jar with properties above
Reading lexicon /opt/termolator/termolator_app/models/Jet4.dict
39811 lexical entries read
Reading lexicon /opt/termolator/termolator_app/models/titles.dict
87 lexical entries read
Loading gazetteer.
Processing background/US20070000135A1-20070104.txt3;background/US20070000135A1-20070104.fact2   read: 52 ms     length: 8055 bytes      annotate: 132 ms        write: 55 ms
Processing background/US20070000194A1-20070104.txt3;background/US20070000194A1-20070104.fact2   read: 112 ms    length: 56420 bytes     annotate: 259 ms        write: 70 ms
Processing background/US20070000212A1-20070104.txt3;background/US20070000212A1-20070104.fact2   read: 11 ms     length: 31747 bytes     annotate: 45 ms write: 11 ms
Processing background/US20070000248A1-20070104.txt3;background/US20070000248A1-20070104.fact2   read: 38 ms     length: 27855 bytes     annotate: 127 ms        write: 23 ms
Processing background/US20070000321A1-20070104.txt3;background/US20070000321A1-20070104.fact2   read: 25 ms     length: 36779 bytes     annotate: 146 ms        write: 22 ms
Processing background/US20070000330A1-20070104.txt3;background/US20070000330A1-20070104.fact2   read: 38 ms     length: 57608 bytes     annotate: 241 ms        write: 44 ms
Processing background/US20070000433A1-20070104.txt3;background/US20070000433A1-20070104.fact2   read: 16 ms     length: 20417 bytes     annotate: 82 ms write: 15 ms
Processing background/US20070000456A1-20070104.txt3;background/US20070000456A1-20070104.fact2   read: 32 ms     length: 55029 bytes     annotate: 179 ms        write: 43 ms
Processing background/US20070000621A1-20070104.txt3;background/US20070000621A1-20070104.fact2   read: 10 ms     length: 22498 bytes     annotate: 93 ms write: 14 ms
Processing background/US20070000633A1-20070104.txt3;background/US20070000633A1-20070104.fact2   read: 7 ms      length: 22623 bytes     annotate: 67 ms write: 11 ms
Processing background/US20070000727A1-20070104.txt3;background/US20070000727A1-20070104.fact2   read: 7 ms      length: 21101 bytes     annotate: 58 ms write: 9 ms
Processing background/US20070000799A1-20070104.txt3;background/US20070000799A1-20070104.fact2   read: 6 ms      length: 14505 bytes     annotate: 60 ms write: 9 ms
Processing background/US20070000817A1-20070104.txt3;background/US20070000817A1-20070104.fact2   read: 7 ms      length: 16238 bytes     annotate: 61 ms write: 9 ms
Processing background/US20070000843A1-20070104.txt3;background/US20070000843A1-20070104.fact2   read: 13 ms     length: 26851 bytes     annotate: 107 ms        write: 16 ms
Processing background/US20070000888A1-20070104.txt3;background/US20070000888A1-20070104.fact2   read: 9 ms      length: 25900 bytes     annotate: 85 ms write: 11 ms
Processing background/US20070000934A1-20070104.txt3;background/US20070000934A1-20070104.fact2   read: 17 ms     length: 37253 bytes     annotate: 162 ms        write: 16 ms
Processing background/US20070001010A1-20070104.txt3;background/US20070001010A1-20070104.fact2   read: 33 ms     length: 73504 bytes     annotate: 289 ms        write: 34 ms
Processing background/US20070001285A1-20070104.txt3;background/US20070001285A1-20070104.fact2   read: 21 ms     length: 45146 bytes     annotate: 186 ms        write: 23 ms
Processing background/US20070001303A1-20070104.txt3;background/US20070001303A1-20070104.fact2   read: 12 ms     length: 28485 bytes     annotate: 111 ms        write: 12 ms
Processing background/US20070001315A1-20070104.txt3;background/US20070001315A1-20070104.fact2   read: 22 ms     length: 71391 bytes     annotate: 193 ms        write: 28 ms
Processing background/US20070001447A1-20070104.txt3;background/US20070001447A1-20070104.fact2   read: 20 ms     length: 32183 bytes     annotate: 121 ms        write: 19 ms
Processing background/US20070001617A1-20070104.txt3;background/US20070001617A1-20070104.fact2   read: 27 ms     length: 51049 bytes     annotate: 175 ms        write: 26 ms
Processing background/US20070001646A1-20070104.txt3;background/US20070001646A1-20070104.fact2   read: 46 ms     length: 96362 bytes     annotate: 292 ms        write: 26 ms
Processing background/US20070001692A1-20070104.txt3;background/US20070001692A1-20070104.fact2   read: 16 ms     length: 52833 bytes     annotate: 157 ms        write: 15 ms
Processing background/US20070001705A1-20070104.txt3;background/US20070001705A1-20070104.fact2   read: 16 ms     length: 62236 bytes     annotate: 144 ms        write: 14 ms
Processing background/US20070001745A1-20070104.txt3;background/US20070001745A1-20070104.fact2   read: 4 ms      length: 21131 bytes     annotate: 27 ms write: 3 ms
Processing background/US20070001758A1-20070104.txt3;background/US20070001758A1-20070104.fact2   read: 8 ms      length: 22661 bytes     annotate: 62 ms write: 6 ms
Processing background/US20070001784A1-20070104.txt3;background/US20070001784A1-20070104.fact2   read: 17 ms     length: 47940 bytes     annotate: 148 ms        write: 15 ms
Processing background/US20070001796A1-20070104.txt3;background/US20070001796A1-20070104.fact2   read: 17 ms     length: 30837 bytes     annotate: 120 ms        write: 11 ms
Processing background/US20070001829A1-20070104.txt3;background/US20070001829A1-20070104.fact2   read: 5 ms      length: 11603 bytes     annotate: 47 ms write: 4 ms
Processing background/US20070001871A1-20070104.txt3;background/US20070001871A1-20070104.fact2   read: 13 ms     length: 28494 bytes     annotate: 112 ms        write: 11 ms
Processing background/US20070001914A1-20070104.txt3;background/US20070001914A1-20070104.fact2   read: 5 ms      length: 14553 bytes     annotate: 41 ms write: 4 ms
Processing background/US20070001918A1-20070104.txt3;background/US20070001918A1-20070104.fact2   read: 19 ms     length: 62188 bytes     annotate: 175 ms        write: 20 ms
Processing background/US20070001924A1-20070104.txt3;background/US20070001924A1-20070104.fact2   read: 61 ms     length: 151231 bytes    annotate: 403 ms        write: 39 ms
Processing background/US20070001935A1-20070104.txt3;background/US20070001935A1-20070104.fact2   read: 16 ms     length: 38629 bytes     annotate: 145 ms        write: 14 ms
Processing background/US20070001945A1-20070104.txt3;background/US20070001945A1-20070104.fact2   read: 92 ms     length: 168057 bytes    annotate: 592 ms        write: 58 ms
Processing background/US20070001951A1-20070104.txt3;background/US20070001951A1-20070104.fact2   read: 10 ms     length: 30995 bytes     annotate: 107 ms        write: 10 ms
Processing background/US20070002028A1-20070104.txt3;background/US20070002028A1-20070104.fact2   read: 21 ms     length: 67565 bytes     annotate: 197 ms        write: 19 ms
Processing background/US20070002187A1-20070104.txt3;background/US20070002187A1-20070104.fact2   read: 10 ms     length: 18244 bytes     annotate: 72 ms write: 9 ms
Processing background/US20070002207A1-20070104.txt3;background/US20070002207A1-20070104.fact2   read: 11 ms     length: 18286 bytes     annotate: 75 ms write: 10 ms
Processing background/US20070002229A1-20070104.txt3;background/US20070002229A1-20070104.fact2   read: 19 ms     length: 30489 bytes     annotate: 122 ms        write: 16 ms
Processing background/US20070002383A1-20070104.txt3;background/US20070002383A1-20070104.fact2   read: 30 ms     length: 55027 bytes     annotate: 193 ms        write: 25 ms
Processing background/US20070002424A1-20070104.txt3;background/US20070002424A1-20070104.fact2   read: 19 ms     length: 30778 bytes     annotate: 116 ms        write: 15 ms
Processing background/US20070002544A1-20070104.txt3;background/US20070002544A1-20070104.fact2   read: 11 ms     length: 18583 bytes     annotate: 70 ms write: 10 ms
Processing background/US20070002610A1-20070104.txt3;background/US20070002610A1-20070104.fact2   read: 20 ms     length: 32436 bytes     annotate: 130 ms        write: 16 ms
Processing background/US20070002691A1-20070104.txt3;background/US20070002691A1-20070104.fact2   read: 14 ms     length: 25629 bytes     annotate: 89 ms write: 12 ms
Processing background/US20070002792A1-20070104.txt3;background/US20070002792A1-20070104.fact2   read: 56 ms     length: 105713 bytes    annotate: 356 ms        write: 66 ms
Processing background/US20070002886A1-20070104.txt3;background/US20070002886A1-20070104.fact2   read: 9 ms      length: 19946 bytes     annotate: 83 ms write: 8 ms
Processing background/US20070002941A1-20070104.txt3;background/US20070002941A1-20070104.fact2   read: 6 ms      length: 52254 bytes     annotate: 61 ms write: 5 ms
Processing background/US20070002989A1-20070104.txt3;background/US20070002989A1-20070104.fact2   read: 6 ms      length: 21838 bytes     annotate: 56 ms write: 6 ms
Processing background/US20070003009A1-20070104.txt3;background/US20070003009A1-20070104.fact2   read: 35 ms     length: 86048 bytes     annotate: 319 ms        write: 32 ms
Processing background/US20070003032A1-20070104.txt3;background/US20070003032A1-20070104.fact2   read: 20 ms     length: 46271 bytes     annotate: 174 ms        write: 17 ms
Processing background/US20070003078A1-20070104.txt3;background/US20070003078A1-20070104.fact2   read: 15 ms     length: 35333 bytes     annotate: 135 ms        write: 14 ms
Processing background/US20070003166A1-20070104.txt3;background/US20070003166A1-20070104.fact2   read: 23 ms     length: 61720 bytes     annotate: 208 ms        write: 21 ms
Processing background/US20070003268A1-20070104.txt3;background/US20070003268A1-20070104.fact2   read: 19 ms     length: 44388 bytes     annotate: 168 ms        write: 16 ms
Processing background/US20070003269A1-20070104.txt3;background/US20070003269A1-20070104.fact2   read: 22 ms     length: 65924 bytes     annotate: 209 ms        write: 21 ms
Processing background/US20070003348A1-20070104.txt3;background/US20070003348A1-20070104.fact2   read: 8 ms      length: 22280 bytes     annotate: 76 ms write: 7 ms
Processing background/US20070003438A1-20070104.txt3;background/US20070003438A1-20070104.fact2   read: 8 ms      length: 47696 bytes     annotate: 77 ms write: 8 ms
Processing background/US20070003560A1-20070104.txt3;background/US20070003560A1-20070104.fact2   read: 14 ms     length: 62423 bytes     annotate: 122 ms        write: 12 ms
Processing background/US20070003564A1-20070104.txt3;background/US20070003564A1-20070104.fact2   read: 20 ms     length: 40003 bytes     annotate: 54 ms write: 6 ms
Processing background/US20070003749A1-20070104.txt3;background/US20070003749A1-20070104.fact2   read: 56 ms     length: 132668 bytes    annotate: 408 ms        write: 43 ms
Processing background/US20070003767A1-20070104.txt3;background/US20070003767A1-20070104.fact2   read: 4 ms      length: 59923 bytes     annotate: 35 ms write: 4 ms
Processing background/US20070003808A1-20070104.txt3;background/US20070003808A1-20070104.fact2   read: 4 ms      length: 31551 bytes     annotate: 41 ms write: 4 ms
Processing background/US20070003821A1-20070104.txt3;background/US20070003821A1-20070104.fact2   read: 17 ms     length: 45355 bytes     annotate: 166 ms        write: 18 ms
Processing background/US20070003896A1-20070104.txt3;background/US20070003896A1-20070104.fact2   read: 9 ms      length: 25582 bytes     annotate: 82 ms write: 9 ms
Processing background/US20070003940A1-20070104.txt3;background/US20070003940A1-20070104.fact2   read: 34 ms     length: 85843 bytes     annotate: 264 ms        write: 29 ms
Processing background/US20070004002A1-20070104.txt3;background/US20070004002A1-20070104.fact2   read: 39 ms     length: 146457 bytes    annotate: 349 ms        write: 41 ms
Processing background/US20070004034A1-20070104.txt3;background/US20070004034A1-20070104.fact2   read: 13 ms     length: 32488 bytes     annotate: 114 ms        write: 12 ms
Processing background/US20070004209A1-20070104.txt3;background/US20070004209A1-20070104.fact2   read: 11 ms     length: 26384 bytes     annotate: 103 ms        write: 11 ms
Processing background/US20070004243A1-20070104.txt3;background/US20070004243A1-20070104.fact2   read: 36 ms     length: 85755 bytes     annotate: 332 ms        write: 37 ms
Processing background/US20070004261A1-20070104.txt3;background/US20070004261A1-20070104.fact2   read: 15 ms     length: 40742 bytes     annotate: 136 ms        write: 15 ms
Processing background/US20070004336A1-20070104.txt3;background/US20070004336A1-20070104.fact2   read: 12 ms     length: 39965 bytes     annotate: 106 ms        write: 11 ms
Processing background/US20070004390A1-20070104.txt3;background/US20070004390A1-20070104.fact2   read: 10 ms     length: 24621 bytes     annotate: 90 ms write: 9 ms
Processing background/US20070004424A1-20070104.txt3;background/US20070004424A1-20070104.fact2   read: 12 ms     length: 27834 bytes     annotate: 108 ms        write: 13 ms
Processing background/US20070004447A1-20070104.txt3;background/US20070004447A1-20070104.fact2   read: 11 ms     length: 25799 bytes     annotate: 100 ms        write: 10 ms
Processing background/US20070004955A1-20070104.txt3;background/US20070004955A1-20070104.fact2   read: 18 ms     length: 44973 bytes     annotate: 156 ms        write: 17 ms
Processing background/US20070004956A1-20070104.txt3;background/US20070004956A1-20070104.fact2   read: 2 ms      length: 20933 bytes     annotate: 24 ms write: 3 ms
Processing background/US20070005012A1-20070104.txt3;background/US20070005012A1-20070104.fact2   read: 8 ms      length: 14203 bytes     annotate: 60 ms write: 8 ms
Processing background/US20070005025A1-20070104.txt3;background/US20070005025A1-20070104.fact2   read: 9 ms      length: 45607 bytes     annotate: 81 ms write: 10 ms
Processing background/US20070005149A1-20070104.txt3;background/US20070005149A1-20070104.fact2   read: 20 ms     length: 43816 bytes     annotate: 180 ms        write: 19 ms
Processing background/US20070005186A1-20070104.txt3;background/US20070005186A1-20070104.fact2   read: 18 ms     length: 47580 bytes     annotate: 156 ms        write: 19 ms
Processing background/US20070005187A1-20070104.txt3;background/US20070005187A1-20070104.fact2   read: 3 ms      length: 28938 bytes     annotate: 24 ms write: 3 ms
Processing background/US20070005196A1-20070104.txt3;background/US20070005196A1-20070104.fact2   read: 29 ms     length: 76818 bytes     annotate: 252 ms        write: 38 ms
Processing background/US20070005248A1-20070104.txt3;background/US20070005248A1-20070104.fact2   read: 27 ms     length: 39796 bytes     annotate: 163 ms        write: 26 ms
Processing background/US20070005314A1-20070104.txt3;background/US20070005314A1-20070104.fact2   read: 30 ms     length: 40799 bytes     annotate: 172 ms        write: 25 ms
Processing background/US20070005373A1-20070104.txt3;background/US20070005373A1-20070104.fact2   read: 39 ms     length: 57559 bytes     annotate: 229 ms        write: 35 ms
Processing background/US20070005401A1-20070104.txt3;background/US20070005401A1-20070104.fact2   read: 41 ms     length: 59638 bytes     annotate: 250 ms        write: 34 ms
Processing background/US20070005425A1-20070104.txt3;background/US20070005425A1-20070104.fact2   read: 29 ms     length: 38565 bytes     annotate: 161 ms        write: 23 ms
Processing background/US20070005426A1-20070104.txt3;background/US20070005426A1-20070104.fact2   read: 90 ms     length: 121697 bytes    annotate: 499 ms        write: 73 ms
Processing background/US20070005453A1-20070104.txt3;background/US20070005453A1-20070104.fact2   read: 22 ms     length: 37312 bytes     annotate: 141 ms        write: 19 ms
Processing background/US20070005620A1-20070104.txt3;background/US20070005620A1-20070104.fact2   read: 20 ms     length: 36484 bytes     annotate: 136 ms        write: 18 ms
Processing background/US20070005629A1-20070104.txt3;background/US20070005629A1-20070104.fact2   read: 64 ms     length: 120622 bytes    annotate: 411 ms        write: 61 ms
Processing background/US20070005659A1-20070104.txt3;background/US20070005659A1-20070104.fact2   read: 16 ms     length: 26360 bytes     annotate: 107 ms        write: 16 ms
Processing background/US20070005681A1-20070104.txt3;background/US20070005681A1-20070104.fact2   read: 27 ms     length: 39187 bytes     annotate: 162 ms        write: 23 ms
Processing background/US20070005712A1-20070104.txt3;background/US20070005712A1-20070104.fact2   read: 9 ms      length: 34232 bytes     annotate: 59 ms write: 7 ms
Processing background/US20070005760A1-20070104.txt3;background/US20070005760A1-20070104.fact2   read: 26 ms     length: 82147 bytes     annotate: 233 ms        write: 24 ms
Processing background/US20070005990A1-20070104.txt3;background/US20070005990A1-20070104.fact2   read: 34 ms     length: 77488 bytes     annotate: 305 ms        write: 34 ms
Processing background/US20070006067A1-20070104.txt3;background/US20070006067A1-20070104.fact2   read: 11 ms     length: 41619 bytes     annotate: 107 ms        write: 12 ms
Processing background/US20070006112A1-20070104.txt3;background/US20070006112A1-20070104.fact2   read: 28 ms     length: 69684 bytes     annotate: 236 ms        write: 25 ms
Processing background/US20070006167A1-20070104.txt3;background/US20070006167A1-20070104.fact2   read: 15 ms     length: 34936 bytes     annotate: 133 ms        write: 14 ms
calling distributional_component.py in term_extration using foreground and background substring list with output to file surgery.all_terms
Traceback (most recent call last):
  File "/opt/termolator/termolator_app/term_utilities.py", line 1133, in get_my_string_list
    instream = open(input_file)
FileNotFoundError: [Errno 2] No such file or directory: 'foreground/US20070005045A1-20070104.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/termolator/termolator_app/make_termolator_fact_txt_files.py", line 22, in <module>
    if __name__ == '__main__': sys.exit(main(sys.argv))
  File "/opt/termolator/termolator_app/make_termolator_fact_txt_files.py", line 20, in main
    create_termolotator_fact_txt_files(input_file,txt2_file,txt3_file,fact_file)
  File "/opt/termolator/termolator_app/termolator_fact_txt.py", line 116, in create_termolotator_fact_txt_files
    inlinelist  = get_my_string_list(input_file)
  File "/opt/termolator/termolator_app/term_utilities.py", line 1136, in get_my_string_list
    instream = open(input_file,encoding='ISO-8859-1')
FileNotFoundError: [Errno 2] No such file or directory: 'foreground/US20070005045A1-20070104.txt'
/opt/termolator/termolator_app/run_termolator.sh: line 144: [-.2: not found
making foreground fact2 files
Calling Java Consule TJet jar with properties above
Reading lexicon /opt/termolator/termolator_app/models/Jet4.dict
39811 lexical entries read
Reading lexicon /opt/termolator/termolator_app/models/titles.dict
87 lexical entries read
Loading gazetteer.
Processing foreground/US20070005045A1-20070104.txt3;foreground/US20070005045A1-20070104.fact2   read: 53 ms     length: 50357 bytes     annotate: 131 ms        write: 43 ms
Processing foreground/US20070005046A1-20070104.txt3;foreground/US20070005046A1-20070104.fact2   read: 68 ms     length: 25988 bytes     annotate: 169 ms        write: 30 ms
Processing foreground/US20070005047A1-20070104.txt3;foreground/US20070005047A1-20070104.fact2   read: 5 ms      length: 82992 bytes     annotate: 11 ms write: 3 ms
Processing foreground/US20070005048A1-20070104.txt3;foreground/US20070005048A1-20070104.fact2   read: 41 ms     length: 48591 bytes     annotate: 238 ms        write: 63 ms
Processing foreground/US20070005049A1-20070104.txt3;foreground/US20070005049A1-20070104.fact2   read: 9 ms      length: 34646 bytes     annotate: 47 ms write: 8 ms
Processing foreground/US20070005050A1-20070104.txt3;foreground/US20070005050A1-20070104.fact2   read: 25 ms     length: 37665 bytes     annotate: 177 ms        write: 28 ms
Processing foreground/US20070005051A1-20070104.txt3;foreground/US20070005051A1-20070104.fact2   read: 66 ms     length: 75180 bytes     annotate: 372 ms        write: 68 ms
Processing foreground/US20070005052A1-20070104.txt3;foreground/US20070005052A1-20070104.fact2   read: 90 ms     length: 70937 bytes     annotate: 275 ms        write: 45 ms
Processing foreground/US20070005053A1-20070104.txt3;foreground/US20070005053A1-20070104.fact2   read: 30 ms     length: 57145 bytes     annotate: 249 ms        write: 36 ms
Processing foreground/US20070005054A1-20070104.txt3;foreground/US20070005054A1-20070104.fact2   read: 46 ms     length: 94335 bytes     annotate: 409 ms        write: 50 ms
Processing foreground/US20070005055A1-20070104.txt3;foreground/US20070005055A1-20070104.fact2   read: 37 ms     length: 91352 bytes     annotate: 376 ms        write: 41 ms
Processing foreground/US20070005056A1-20070104.txt3;foreground/US20070005056A1-20070104.fact2   read: 39 ms     length: 91987 bytes     annotate: 378 ms        write: 54 ms
Processing foreground/US20070005057A1-20070104.txt3;foreground/US20070005057A1-20070104.fact2   read: 57 ms     length: 91194 bytes     annotate: 405 ms        write: 58 ms
Processing foreground/US20070005058A1-20070104.txt3;foreground/US20070005058A1-20070104.fact2   read: 63 ms     length: 97985 bytes     annotate: 389 ms        write: 57 ms
Processing foreground/US20070005059A1-20070104.txt3;foreground/US20070005059A1-20070104.fact2   read: 41 ms     length: 97553 bytes     annotate: 398 ms        write: 38 ms
Processing foreground/US20070005060A1-20070104.txt3;foreground/US20070005060A1-20070104.fact2   read: 35 ms     length: 89868 bytes     annotate: 362 ms        write: 37 ms
Processing foreground/US20070005061A1-20070104.txt3;foreground/US20070005061A1-20070104.fact2   read: 7 ms      length: 20474 bytes     annotate: 78 ms write: 8 ms
Processing foreground/US20070005062A1-20070104.txt3;foreground/US20070005062A1-20070104.fact2   read: 13 ms     length: 41375 bytes     annotate: 141 ms        write: 14 ms
Processing foreground/US20070005063A1-20070104.txt3;foreground/US20070005063A1-20070104.fact2   read: 29 ms     length: 34816 bytes     annotate: 123 ms        write: 14 ms
Processing foreground/US20070005064A1-20070104.txt3;foreground/US20070005064A1-20070104.fact2   read: 4 ms      length: 20412 bytes     annotate: 39 ms write: 4 ms
Processing foreground/US20070005065A1-20070104.txt3;foreground/US20070005065A1-20070104.fact2   read: 3 ms      length: 11164 bytes     annotate: 32 ms write: 4 ms
Processing foreground/US20070005066A1-20070104.txt3;foreground/US20070005066A1-20070104.fact2   read: 6 ms      length: 16828 bytes     annotate: 67 ms write: 6 ms
Processing foreground/US20070005067A1-20070104.txt3;foreground/US20070005067A1-20070104.fact2   read: 7 ms      length: 12965 bytes     annotate: 60 ms write: 7 ms
Processing foreground/US20070005068A1-20070104.txt3;foreground/US20070005068A1-20070104.fact2   read: 4 ms      length: 12429 bytes     annotate: 40 ms write: 5 ms
Processing foreground/US20070005069A1-20070104.txt3;foreground/US20070005069A1-20070104.fact2   read: 15 ms     length: 37979 bytes     annotate: 127 ms        write: 13 ms
Processing foreground/US20070005070A1-20070104.txt3;foreground/US20070005070A1-20070104.fact2   read: 8 ms      length: 21101 bytes     annotate: 79 ms write: 9 ms
Processing foreground/US20070005071A1-20070104.txt3;foreground/US20070005071A1-20070104.fact2   read: 7 ms      length: 14651 bytes     annotate: 65 ms write: 7 ms
Processing foreground/US20070005072A1-20070104.txt3;foreground/US20070005072A1-20070104.fact2   read: 27 ms     length: 55909 bytes     annotate: 242 ms        write: 25 ms
Processing foreground/US20070005073A1-20070104.txt3;foreground/US20070005073A1-20070104.fact2   read: 10 ms     length: 29916 bytes     annotate: 110 ms        write: 11 ms
Processing foreground/US20070005074A1-20070104.txt3;foreground/US20070005074A1-20070104.fact2   read: 47 ms     length: 99905 bytes     annotate: 413 ms        write: 45 ms
Processing foreground/US20070005075A1-20070104.txt3;foreground/US20070005075A1-20070104.fact2   read: 18 ms     length: 41622 bytes     annotate: 165 ms        write: 20 ms
Processing foreground/US20070005076A1-20070104.txt3;foreground/US20070005076A1-20070104.fact2   read: 20 ms     length: 34068 bytes     annotate: 148 ms        write: 20 ms
Processing foreground/US20070005077A1-20070104.txt3;foreground/US20070005077A1-20070104.fact2   read: 38 ms     length: 51045 bytes     annotate: 228 ms        write: 30 ms
Processing foreground/US20070005078A1-20070104.txt3;foreground/US20070005078A1-20070104.fact2   read: 13 ms     length: 22571 bytes     annotate: 95 ms write: 13 ms
Processing foreground/US20070005079A1-20070104.txt3;foreground/US20070005079A1-20070104.fact2   read: 34 ms     length: 46305 bytes     annotate: 185 ms        write: 24 ms
Processing foreground/US20070005080A1-20070104.txt3;foreground/US20070005080A1-20070104.fact2   read: 27 ms     length: 46346 bytes     annotate: 183 ms        write: 25 ms
Processing foreground/US20070005081A1-20070104.txt3;foreground/US20070005081A1-20070104.fact2   read: 22 ms     length: 49387 bytes     annotate: 164 ms        write: 21 ms
Processing foreground/US20070005082A1-20070104.txt3;foreground/US20070005082A1-20070104.fact2   read: 45 ms     length: 57316 bytes     annotate: 246 ms        write: 46 ms
Processing foreground/US20070005083A1-20070104.txt3;foreground/US20070005083A1-20070104.fact2   read: 13 ms     length: 27342 bytes     annotate: 116 ms        write: 11 ms
Processing foreground/US20070005084A1-20070104.txt3;foreground/US20070005084A1-20070104.fact2   read: 37 ms     length: 95665 bytes     annotate: 406 ms        write: 39 ms
Processing foreground/US20070005085A1-20070104.txt3;foreground/US20070005085A1-20070104.fact2   read: 5 ms      length: 13909 bytes     annotate: 59 ms write: 6 ms
Processing foreground/US20070005086A1-20070104.txt3;foreground/US20070005086A1-20070104.fact2   read: 7 ms      length: 18093 bytes     annotate: 75 ms write: 8 ms
Processing foreground/US20070005087A1-20070104.txt3;foreground/US20070005087A1-20070104.fact2   read: 10 ms     length: 34424 bytes     annotate: 94 ms write: 9 ms
Processing foreground/US20070005088A1-20070104.txt3;foreground/US20070005088A1-20070104.fact2   read: 9 ms      length: 24010 bytes     annotate: 85 ms write: 8 ms
Processing foreground/US20070005089A1-20070104.txt3;foreground/US20070005089A1-20070104.fact2   read: 10 ms     length: 25862 bytes     annotate: 95 ms write: 10 ms
Processing foreground/US20070005090A1-20070104.txt3;foreground/US20070005090A1-20070104.fact2   read: 20 ms     length: 74420 bytes     annotate: 209 ms        write: 19 ms
Processing foreground/US20070005091A1-20070104.txt3;foreground/US20070005091A1-20070104.fact2   read: 11 ms     length: 34831 bytes     annotate: 118 ms        write: 13 ms
Processing foreground/US20070005092A1-20070104.txt3;foreground/US20070005092A1-20070104.fact2   read: 18 ms     length: 42623 bytes     annotate: 185 ms        write: 18 ms
Processing foreground/US20070005093A1-20070104.txt3;foreground/US20070005093A1-20070104.fact2   read: 20 ms     length: 51475 bytes     annotate: 211 ms        write: 21 ms
Processing foreground/US20070005094A1-20070104.txt3;foreground/US20070005094A1-20070104.fact2   read: 43 ms     length: 127227 bytes    annotate: 450 ms        write: 50 ms
Processing foreground/US20070005095A1-20070104.txt3;foreground/US20070005095A1-20070104.fact2   read: 17 ms     length: 45022 bytes     annotate: 199 ms        write: 25 ms
Processing foreground/US20070005096A1-20070104.txt3;foreground/US20070005096A1-20070104.fact2   read: 4 ms      length: 115795 bytes    annotate: 44 ms write: 4 ms
Processing foreground/US20070005097A1-20070104.txt3;foreground/US20070005097A1-20070104.fact2   read: 9 ms      length: 20951 bytes     annotate: 83 ms write: 9 ms
Processing foreground/US20070005098A1-20070104.txt3;foreground/US20070005098A1-20070104.fact2   read: 10 ms     length: 24827 bytes     annotate: 108 ms        write: 11 ms
Processing foreground/US20070005099A1-20070104.txt3;foreground/US20070005099A1-20070104.fact2   read: 11 ms     length: 27442 bytes     annotate: 121 ms        write: 12 ms
Processing foreground/US20070005100A1-20070104.txt3;foreground/US20070005100A1-20070104.fact2   read: 9 ms      length: 22588 bytes     annotate: 100 ms        write: 9 ms
Processing foreground/US20070005101A1-20070104.txt3;foreground/US20070005101A1-20070104.fact2   read: 2 ms      length: 38335 bytes     annotate: 15 ms write: 1 ms
Processing foreground/US20070005102A1-20070104.txt3;foreground/US20070005102A1-20070104.fact2   read: 2 ms      length: 38393 bytes     annotate: 9 ms  write: 1 ms
Processing foreground/US20070005103A1-20070104.txt3;foreground/US20070005103A1-20070104.fact2   read: 14 ms     length: 38233 bytes     annotate: 148 ms        write: 14 ms
Processing foreground/US20070005104A1-20070104.txt3;foreground/US20070005104A1-20070104.fact2   read: 25 ms     length: 59886 bytes     annotate: 266 ms        write: 26 ms
Processing foreground/US20070005105A1-20070104.txt3;foreground/US20070005105A1-20070104.fact2   read: 23 ms     length: 53572 bytes     annotate: 241 ms        write: 24 ms
Processing foreground/US20070005106A1-20070104.txt3;foreground/US20070005106A1-20070104.fact2   read: 15 ms     length: 54653 bytes     annotate: 147 ms        write: 15 ms
Processing foreground/US20070005107A1-20070104.txt3;foreground/US20070005107A1-20070104.fact2   read: 9 ms      length: 24891 bytes     annotate: 103 ms        write: 10 ms
Processing foreground/US20070005108A1-20070104.txt3;foreground/US20070005108A1-20070104.fact2   read: 13 ms     length: 49639 bytes     annotate: 130 ms        write: 13 ms
Processing foreground/US20070005109A1-20070104.txt3;foreground/US20070005109A1-20070104.fact2   read: 8 ms      length: 20693 bytes     annotate: 78 ms write: 7 ms
Processing foreground/US20070005110A1-20070104.txt3;foreground/US20070005110A1-20070104.fact2   read: 13 ms     length: 30418 bytes     annotate: 132 ms        write: 12 ms
Generating POS files
Adjusting for Special Chars
Chunking for inline term detection
INFO:root:RDG Folder: surgery.internal_foreground_substring_list
INFO:root:Reference Folder: surgery.internal_background_substring_list
INFO:root:Measure: Weighted
INFO:root:Test Word List File: None
DEBUG:root:Loading Files...
DEBUG:root:Loading general documents from surgery.internal_background_substring_list
DEBUG:root:Loading RDG from surgery.internal_foreground_substring_list...
DEBUG:root:done
DEBUG:root:Ranking terms...
DEBUG:root:Entering rankTerms, loading keys...
DEBUG:root:Done
DEBUG:root:Measuring ranks...
DEBUG:root:Measuring word 1000
DEBUG:root:Measuring word 2000
DEBUG:root:Measuring word 3000
DEBUG:root:Measuring word 4000
DEBUG:root:Measuring word 5000
DEBUG:root:Measuring word 6000
DEBUG:root:Measuring word 7000
DEBUG:root:Measuring word 8000
DEBUG:root:Measuring word 9000
DEBUG:root:Measuring word 10000
DEBUG:root:Done
DEBUG:root:Sorting...
DEBUG:root:Done
calling filter_term_output.py with filter_term_output.py surgery surgery.webscore True 30000 False
Final terms can be found in surgery.out_term_list from the scored file in surgery.scored_output
Cleaning up files
```

**Comment by vladtco** [comment]
Regarding `/opt/termolator/termolator_app/run_termolator.sh: line 144: [-.2: not found`, the expression on the line https://github.com/AdamMeyers/The_Termolator/blob/master/run_termolator.sh#L117 should be wrapped in spaces between "[" and "]".

**Comment by vladtco** [comment]
Fixed in https://github.com/AdamMeyers/The_Termolator/commit/8c3297ac969f1295f35ba839062d83eb4307f15d, closing
